---
- hosts: ios
  tasks:
  - name: "Add Static IP Address to Interface G2"
    ios_config:
      provider: "{{cli}}"
      parents:
        - "interface GigabitEthernet2"
      lines:
        - "no shutdown"
  - name: "Remove now moot due to VRF default static route"
    ios_config:
      provider: "{{cli}}"
      lines:
        - "no ip route 0.0.0.0 0.0.0.0 GigabitEthernet1 {{router_a_addressg1NH}}"


