---
- hosts: "{{ target }}"
  vars_files:
    - "provider_vars/{{ cloud_provider }}.yml"
  tasks:
  - name: "Disable Smart License"
    ios_config:
      provider: "{{cli}}"
      lines:
        - "no license smart enable"
