---
- name: Configure Cloud Router
  hosts: "{{ target }}"
  vars_files:
      - "~/PycharmProjects/ThinSecurityStack/DB/dmvpn_tunnel_nhs_addresses.yml"
      - "provider_vars/{{ cloud_provider }}.yml"
  roles:
    - "create_csr1000v_hub_a"